version: 1.0.{build}
image: Visual Studio 2017
environment:
  PreReleaseSuffix: alpha
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  COVERALLS_REPO_TOKEN:
    secure: D248Kn+z16JEn6Y5aWARHp7R7TNObR3vHtIU3susaaXfwi8VcRLsyOO9eg9/9cOU
  SkipCodeInspect: true
build_script:
- ps: .\build.ps1 -Target AppVeyor
test: off
artifacts:
- path: artifacts/packages/*.nupkg
- path: artifacts/coverage/*.xml
- path: artifacts/test-results/*.xml
- path: artifacts/resharper-reports/*.xml
- path: artifacts/resharper-reports/*.html
- path: artifacts/coverage/coverage.dcvr
- path: artifacts/test-results/*.trx
deploy:
- provider: NuGet
  server: https://www.myget.org/F/alhardy/api/v2/package
  api_key:
    secure: gIAiACgNj+JzXyLLTe3rLxZyrAB9RpC8Lw81xEjdOLXqotprqEwGiFWRipEqkpps
  skip_symbols: true